### Required Assignment 19.1: Collaborative Filtering

**Expected Time = 90 minutes**

**Total Points = 50**

In this activity, you will use collaborative filtering to predict user ratings.  This iterative process will begin with our simple reviews dataset to fill in the missing values for the users.  Your regression models will be built using Scikit-Learn's `LinearRegression` estimator.

### Index


- [Problem 1](#-Problem-1)
- [Problem 2](#-Problem-2)
- [Problem 3](#-Problem-3)
- [Problem 4](#-Problem-4)
- [Problem 5](#-Problem-5)
- [Problem 6](#-Problem-6)

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

### The Data

Again, you begin with data indexed by artists.  You will add random values for `F1` and `F2`, and use these to create regression models for each user.  Then, tracking the coefficients -- you create new artist vectors, and repeat the process.  The goal remains to predict user ratings of unrated albums.

In [8]:
reviews = pd.read_csv('/content/sample_data/user_rated.csv', index_col = 0).iloc[:, :-2].T

In [9]:
reviews

                 Alfred  Mandy  Lenny  Joan  Tino
Michael Jackson     3.0    NaN    2.0   3.0   1.0
Clint Black         4.0    9.0    5.0   NaN   1.0
Dropdead            NaN    NaN    8.0   9.0   NaN
Anti-Cimex          4.0    3.0    9.0   4.0   9.0
Cardi B             4.0    8.0    NaN   9.0   5.0

[Back to top](#-Index)

### Problem 1

### Creating F1 and F2

**5 Points**

To begin, create two randomly instantiated vectors `F1` and `F2` as columns in your DataFrame.  To do so, you will draw numbers from a random normal distribution using `np.random.normal(size = 5)`.  Set `np.random.seed(42)`.

In [15]:
np.random.seed(42)

In [16]:
### GRADED
reviews['F1'] = ''
reviews['F2'] = ''

# YOUR CODE HERE
reviews['F1']=np.random.normal(size=5)
reviews['F2']=np.random.normal(size=5)

### ANSWER CHECK
reviews

                 Alfred  Mandy  Lenny  Joan  Tino        F1        F2
Michael Jackson     3.0    NaN    2.0   3.0   1.0  0.496714 -0.234137
Clint Black         4.0    9.0    5.0   NaN   1.0 -0.138264  1.579213
Dropdead            NaN    NaN    8.0   9.0   NaN  0.647689  0.767435
Anti-Cimex          4.0    3.0    9.0   4.0   9.0  1.523030 -0.469474
Cardi B             4.0    8.0    NaN   9.0   5.0 -0.234153  0.542560

[Back to top](#-Index)

### Problem 2

#### Regression models for all users

**10 Points**

Complete the starter code given below to iterate over the first five columns of the `reviews` dataframe. To define `X`, drop the rows where the column `c` is NaN and selects the `F1` and `F2` columns. The target variable `y` is set to the column `c` after dropping NaNs.

Next, use `X` and `y` to fit a linear regression model without an intercept to predict values of column `c` based on `F1` and `F2`. Assign this model to the variable `lr`.

Store the coefficients of the linear regression model  in the list `uf` and convert this list to a NumPy array.

In [18]:
reviews

                 Alfred  Mandy  Lenny  Joan  Tino        F1        F2
Michael Jackson     3.0    NaN    2.0   3.0   1.0  0.496714 -0.234137
Clint Black         4.0    9.0    5.0   NaN   1.0 -0.138264  1.579213
Dropdead            NaN    NaN    8.0   9.0   NaN  0.647689  0.767435
Anti-Cimex          4.0    3.0    9.0   4.0   9.0  1.523030 -0.469474
Cardi B             4.0    8.0    NaN   9.0   5.0 -0.234153  0.542560

Complete the starter code given below to iterate over the first five columns of the reviews dataframe. To define X, drop the rows where the column **col** is NaN and selects the F1 and F2 columns. The target variable y is set to the column c after dropping NaNs.

Next, use X and y to fit a linear regression model without an intercept to predict values of column c based on F1 and F2. Assign this model to the variable lr.

Store the coefficients of the linear regression model in the list uf and convert this list to a NumPy array.

In [28]:
alfred_nn=reviews[reviews['Alfred'].isna()==False]
alfred_nn['Alfred']

Michael Jackson    3.0
Clint Black        4.0
Anti-Cimex         4.0
Cardi B            4.0
Name: Alfred, dtype: float64

In [31]:
### GRADED
uf = list()
# YOUR CODE HERE
for col in reviews.columns[:-2]:
  col_nn=reviews[reviews[col].isna()==False]
  X = col_nn[['F1','F2']]
  y = col_nn[col]
  lr = LinearRegression(fit_intercept=False).fit(X,y)
  coefs = lr.coef_
  uf.append(coefs)

uf =np.array(uf)

### ANSWER CHECK
uf.shape #should be (5, 2)

(5, 2)

[Back to top](#-Index)

### Problem 3

#### New Model for artists

**10 Points**

Below, a dataframe `ui_df` is created using the coefficients from the previous problem.  Now, you are to use this data with `F1` and `F2` to build a new model and track each *artists* coefficients.  Assign this as a numpy array to `ifs` below.

HINT: The steps for this problem are similar to the ones in Problem 2.

In [ ]:
ui_df = reviews.iloc[:, :-2].T
ui_df['F1'] = uf[:, 0]
ui_df['F2'] = uf[:, 1]
ui_df

In [ ]:
### GRADED
ifs = ''


# YOUR CODE HERE
raise NotImplementedError()

### ANSWER CHECK
ifs.shape

[Back to top](#-Index)

### Problem 4

#### New model for users

**10 Points**

Below, a dataframe is created using the coefficients from our linear model on artists -- `if_df`.  You are to use this data to create new arrays of coefficients for the users.  Assign this array of coefficients as `uf2`.


HINT: The steps for this problem are similar to the ones in Problem 2.

In [ ]:
if_df = reviews.copy().iloc[:, :-2]
if_df.loc[:, 'F1'] = ifs[:, 0]
if_df.loc[:, 'F2'] = ifs[:, 1]
if_df

In [ ]:
### GRADED
uf2 = ''


# YOUR CODE HERE
raise NotImplementedError()

### ANSWER CHECK
uf2

[Back to top](#-Index)

### Problem 5

#### One more iteration

**5 Points**

Below, a dataframe `ui_df2` is created using the results of `uf2`.  Use the features `F1` and `F2` to create regression models for each user and track the coefficients in `ifs2`.

HINT: The steps for this problem are similar to the ones in Problem 2.

In [ ]:
ui_df2 = reviews.copy().iloc[:, :-2].T
ui_df2['F1'] = uf2[:, 0]
ui_df2['F2'] = uf2[:, 1]
ui_df2

In [ ]:
### GRADED
ifs2 = ''


# YOUR CODE HERE
raise NotImplementedError()

### ANSWER CHECK
ifs2

[Back to top](#-Index)

### Problem 6

#### Comparing Models

**10 Points**

Based on the first iteration resulting in `if_df` and the last in `if_df2` use these different item factors as inputs to a `LinearRegression` model to determine the `mean_squared_error` for each model for Alfred.  Which user factors did a better job as inputs to the model -- `if_df` or `if_df2`.  Assign your answer as a string to `ans6` below.

In [ ]:
if_df2 = reviews.copy().iloc[:, :-2]
if_df2.loc[:, 'F1'] = ifs2[:, 0]
if_df2.loc[:, 'F2'] = ifs2[:, 1]
if_df2

In [ ]:
if_df.to_csv('data/Q.csv')
ui_df.to_csv('data/P.csv')

In [ ]:
(ui_df[['F1', 'F2']]@if_df[['F1', 'F2']].T).T

In [ ]:
reviews

In [ ]:
(ui_df2[['F1', 'F2']]@if_df2[['F1', 'F2']].T).T

In [ ]:
if_df[['F1', 'F2']]

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
### GRADED
ans6 = ''


# YOUR CODE HERE
raise NotImplementedError()

### ANSWER CHECK
ans6